### ISSUE TITLE
Dividers, padding, and font size

### ISSUE THREAD

**Issue by afollestad** [kennydude/AwesomePrefs#2]
The system dividers should be re-added so they look more like native settings. Also, padding around items and font size needs to be tweaked so it matches the native settings.

**Comment by kennydude** [comment]
Okay, will fix as soon as I can

**Comment by afollestad** [comment]
Awesome!

**Comment by kennydude** [comment]
I got dividers working, however Eclipse is being a pain. Code will be up soon
